# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCKxEwvHAXKPbEIvB-qk5hgf6saq-2c-
"""

import pandas as pd
baza={
    "|FISH":[ "Mammadov Mammad" , "Hasanov Hasan" , "Rahimov Rahim" , "Guliyev Gul" , "Abdullayev Abdulla" ,"Mahbuba", "Shahnoza", "Gulnoza", "Dilnoza", "Nodira" ],
    "YOSHI":["12", "13", "14", "15", "16", "17", "18", "19", "20", "21"],
    "JINSI":[ "ERKAK" , "ERKAK", "ERKAK" , "ERKAK" , "ERKAK", "AYOL", "AYOL", "AYOL", "AYOL", "AYOL" ],
    "MAKTABI":["1-maktab", "2-maktab", "3-maktab", "4-maktab", "5-maktab", "6-maktab", "7-maktab", "8-maktab", "9-maktab" , "10-maktab"],
    "tel raqami":["+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 ", "+998911249154 " ],

}

db=pd.DataFrame(baza)
print(db)

filtr=db[db['JINSI']=='AYOL']
print(filtr)

filtr=db[(db['JINSI']=='AYOL') & (db['YOSHI']>"15")]
print(filtr)

from google.colab import drive
drive.mount('/content/drive')